auto: true

markdown:    maruku
paginate:    10
permalink:   /:year/:month/:day/:title

url:         http://floriangeierde.github.com/floriangeierde
title:       Florian Geier

exclude:     screen.scss, Gemfile, Gemfile.lock